//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public int ID { get; set; }
        public string Título { get; set; }
        public int Año { get; set; }
        public Nullable<int> IDAutor { get; set; }
    
        public virtual Autores Autores { get; set; }
    }
}
