USE [master]
GO

/****** Object:  Database [SistemaGestionLibros]    Script Date: 9/30/2023 11:38:46 AM ******/
CREATE DATABASE [SistemaGestionLibros]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SistemaGestionLibros', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.ADVENTUREWORKS\MSSQL\DATA\SistemaGestionLibros.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SistemaGestionLibros_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.ADVENTUREWORKS\MSSQL\DATA\SistemaGestionLibros_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SistemaGestionLibros].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SistemaGestionLibros] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET ARITHABORT OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SistemaGestionLibros] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SistemaGestionLibros] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SistemaGestionLibros] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SistemaGestionLibros] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SistemaGestionLibros] SET  MULTI_USER 
GO

ALTER DATABASE [SistemaGestionLibros] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SistemaGestionLibros] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SistemaGestionLibros] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SistemaGestionLibros] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SistemaGestionLibros] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SistemaGestionLibros] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SistemaGestionLibros] SET QUERY_STORE = ON
GO

ALTER DATABASE [SistemaGestionLibros] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SistemaGestionLibros] SET  READ_WRITE 
GO


